FROM ruby:3.3.6

RUN apt-get update -qq && \
    apt-get install -y nodejs build-essential postgresql-client

WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

EXPOSE 3000
CMD ["bash", "-lc", "bundle exec rails server -b 0.0.0.0 -p 3000"]
